app/urls.py
from django.http import HttpResponse
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.conf.urls.static import static

from proyectoweb import settings
from .views import (
    BuscarDireccion,
    SolicitudesApoderados,
    Vinculaciones,
    asignar_alumnos,
    buscar_colegios,
    gestion_alumnos,
    gestionar_vehiculos,

    home,
    listar_conductores,
  
    registro_conductor,
    registro_apoderado,
    CustomLoginView,
    home_conductor,
    home_apoderado,
 
    crear_solicitud_vinculacion,
    simulador_recorrido,
    subir_datos_vehiculo,
    subir_documentos,
    ver_alumnos_vinculados,
    ver_conductor_alumno,
    ver_documentos_conductor,
    visualizar_recorrido,

)
from app import views

urlpatterns = [
    path('', home, name='home'),  # Página de inicio
    path('login/', CustomLoginView.as_view(), name='login'),
    path('registro/conductor/', registro_conductor, name='registro_conductor'),
    path('registro/apoderado/', registro_apoderado, name='registro_apoderado'),
    path('home/conductor/', home_conductor, name='home_conductor'),
    path('home/apoderado/', home_apoderado, name='home_apoderado'),
    path('pagina/no_autorizada/', lambda request: HttpResponse("No autorizado"), name='pagina_no_autorizada'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('registro/alumno/', views.crear_alumno, name='crear_alumno'),
    path('buscar/conductor/', views.buscar_conductor, name='buscar_conductor'),  # Asegúrate de que esta línea esté presente
    path('crear/solicitud/<int:conductor_id>/', views.crear_solicitud_vinculacion, name='crear_solicitud_vinculacion'),
    path('vinculaciones/', Vinculaciones.as_view(), name='vinculaciones'),
    path('solicitudes_apoderado/', SolicitudesApoderados.as_view(), name='SolicitudesApoderados'),
    path('ver-conductor-alumno/', ver_conductor_alumno, name='ver_conductor_alumno'),  # Nueva URL
    path('listar_conductores/', listar_conductores, name='listar_conductores'),
    path('gestion_alumnos/', gestion_alumnos, name='gestion_alumnos'),
    path('subir_documentos/', subir_documentos, name='subir_documentos'),
    path('subir_datos_vehiculo/', subir_datos_vehiculo, name='subir_datos_vehiculo'),
    path('conductor/gestionar_documentos/', views.gestionar_documentos, name='gestionar_documentos'),
    path('ver_documentos_conductor/<int:conductor_id>/', ver_documentos_conductor, name='ver_documentos_conductor'),
    path('documentos/conductor/<int:conductor_id>/', views.ver_documentos_conductor, name='ver_documentos_conductor'),
    path('listar_conductores/', listar_conductores, name='listar_conductores'),
    path('chat/<str:chat_id>/', views.chat_view, name='chat_view'),
    path('mensaje/', views.ver_mensajes, name='ver_mensajes'),
    path('mensaje/enviar/', views.enviar_mensaje, name='enviar_mensaje'),
    path('mensaje/<int:conversacion_id>/', views.ver_conversacion, name='ver_conversacion'),
    path('mensaje/enviar/<int:conversacion_id>/', views.enviar_mensaje, name='enviar_mensaje'),
    path('mensaje/cargar_conversacion/<int:conversacion_id>/', views.cargar_conversacion, name='cargar_conversacion'),
    path('elegir-tipo-registro/', views.elegir_tipo_registro, name='elegir_tipo_registro'),
    path('datos-personales/', views.datos_personales, name='datos_personales'),
    path('buscar-colegios/', buscar_colegios, name='buscar_colegios'),
    path('buscar_direccion/', BuscarDireccion.as_view(), name='buscar_direccion'),
    path('quitar_alumno/', views.quitar_alumno, name='quitar_alumno'),

    path('ver_alumnos_vinculados/', ver_alumnos_vinculados, name='ver_alumnos_vinculados'),
    path('gestionar_rutas/', views.gestionar_rutas, name='gestionar_rutas'),
    path('asignar_alumnos/', asignar_alumnos, name='asignar_alumnos'),  # Asegúrate de que esta línea esté presente
    path('visualizar_recorrido/<int:ruta_id>/', visualizar_recorrido, name='visualizar_recorrido'),
    path('elegir-ruta/', views.elegir_ruta, name='elegir_ruta'),
    path('simulador/<int:ruta_id>/', simulador_recorrido, name='simulador_recorrido'),
    path('gestionar_vehiculos/', gestionar_vehiculos, name='gestionar_vehiculos'),

    path('gestionar_vehiculos/<int:vehiculo_id>/', gestionar_vehiculos, name='gestionar_vehiculos_edit'),  # Acepta un ID
    path('ver_rutas_asignadas/', views.ver_rutas_asignadas, name='ver_rutas_asignadas'),
    path('ver_ruta_completa/<int:alumno_id>/', views.ver_ruta_completa_apoderado, name='ver_ruta_completa_apoderado'),
    path('ver_historial_viajes/<int:ruta_id>/', views.ver_historial_viajes, name='ver_historial_viajes'),
    path('iniciar_viaje/<int:ruta_id>/', views.iniciar_viaje, name='iniciar_viaje'),

    # Rutas del apoderado

    # Rutas del conductor


    # Solicitudes de vinculación
    path('crear_solicitud/', crear_solicitud_vinculacion, name='crear_solicitud'),


    # URL para gestionar solicitudes de un conductor

 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoweb/urls.py
from django.contrib import admin

from django.urls import path, include, re_path
from django.conf.urls.static import static

from proyectoweb import settings
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),  # Incluye las URLs de la app
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from datetime import timezone
from pyexpat.errors import messages
from django.db import models
from django.contrib.auth import get_user_model

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone

from proyectoweb import settings
# Gestor de usuario personalizado
class CustomUserManager(BaseUserManager):
    def create_user(self, rut, email, nombre, apellido, password=None, **extra_fields):
        if not rut:
            raise ValueError('El usuario debe tener un RUT')
        if not email:
            raise ValueError('El usuario debe tener un correo electrónico')
        if not nombre:
            raise ValueError('El usuario debe tener un nombre')
        if not apellido:
            raise ValueError('El usuario debe tener un apellido')

        email = self.normalize_email(email)
        user = self.model(rut=rut, email=email, nombre=nombre, apellido=apellido, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, rut, email, nombre, apellido, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(rut, email, nombre, apellido, password, **extra_fields)

# Modelo de usuario personalizado
class CustomUser(AbstractBaseUser):
    rut = models.CharField(max_length=12, unique=True)
    nombre = models.CharField(max_length=30, null=False, default='Desconocido')  # Añade un valor por defecto
    apellido = models.CharField(max_length=30, null=False, default='Desconocido')  # Añade un valor por defecto
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'rut'
    REQUIRED_FIELDS = ['email', 'nombre', 'apellido']
    def __str__(self):
        return f'{self.nombre} {self.apellido} ({self.rut})'

# Modelo Apoderado
class Apoderado(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    relacion_alumno = models.CharField(max_length=50)
    conductores = models.ManyToManyField('Conductor', related_name='apoderado_conductores')  # Cambiado el related_name
    nombre = models.CharField(max_length=100, blank=True, null=True)  
    apellido = models.CharField(max_length=100, null=True)
    def __str__(self):
        return f"{self.user.rut} - Apoderado"

# Modelo Conductor
class Conductor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, blank=True, null=True)  
    apellido = models.CharField(max_length=100, null=True)
    disponible = models.BooleanField(default=True)  # Eliminar esta línea

    licencia_conduccion = models.CharField(max_length=20)
    licencia = models.FileField(upload_to='licencias/', blank=True, null=True)
    certificado = models.FileField(upload_to='certificados/', blank=True, null=True)
    apoderados = models.ManyToManyField('Apoderado', related_name='conductor_apoderados')  # Cambiado el related_name
    documentos_personales_subidos = models.BooleanField(default=False)
    datos_vehiculo_subidos = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.user.rut} - Conductor"
    
class Vehiculo(models.Model):
    conductor = models.ForeignKey(Conductor, on_delete=models.CASCADE, related_name='vehiculos')
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    anio = models.IntegerField()
    patente = models.CharField(max_length=10)
    revision_tecnica = models.FileField(upload_to='documentos_vehiculo/')
    seguro_obligatorio = models.FileField(upload_to='documentos_vehiculo/')
    lat = models.FloatField()
    lng = models.FloatField()
    def __str__(self):
        return f"{self.marca} {self.modelo} - Patente: {self.patente}"

class Colegio(models.Model):
    nombre_rbd = models.CharField(max_length=255)
    nombre_region = models.CharField(max_length=255)
    nombre_comuna = models.CharField(max_length=255)
    nombre_deprov = models.CharField(max_length=255)
    latitud = models.FloatField()
    longitud = models.FloatField()

    def __str__(self):
        return self.nombre_rbd
    
    # Modelo Alumno
class Alumno(models.Model):
    rut = models.CharField(max_length=12, unique=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    edad = models.PositiveIntegerField()
    colegio = models.ForeignKey(Colegio, on_delete=models.CASCADE, related_name='alumnos')
    apoderado = models.ForeignKey(Apoderado, on_delete=models.CASCADE, related_name='alumnos')
    rutas = models.ManyToManyField('Ruta', related_name='alumnos_rutas', blank=True)  # Asegúrate de que esto esté aquí
    direccion = models.CharField(max_length=255, null=True, blank=True)  # Nuevo campo para la dirección
    conductor = models.ForeignKey(Conductor, null=True, blank=True, on_delete=models.SET_NULL, related_name='alumnos')
    latitud = models.FloatField(null=True, blank=True)  # Permitir nulos si es necesario
    longitud = models.FloatField(null=True, blank=True)
    def __str__(self):
        return self.nombre
    




class Ruta(models.Model):
    conductor = models.ForeignKey(Conductor, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)  # Identificación de la ruta
    apoderados = models.ManyToManyField(Apoderado)  # Relación de muchos a muchos con Apoderado
    destino = models.CharField(max_length=255)  # Destino final de la ruta
    puntos_intermedios = models.JSONField(null=True, blank=True)  # Puntos por donde debe pasar
    hora_inicio = models.TimeField(null=True)  # Hora estimada de inicio de la ruta (opcional ahora)
    hora_fin = models.TimeField(null=True, blank=True)  # Hora estimada de fin de la ruta
    paradas = models.JSONField(default=list)  # Almacena las coordenadas de las paradas en formato JSON
    dias = models.JSONField(default=list)  # Almacena una lista de días: ["lunes", "martes", "miércoles", ...]

    estado = models.CharField(max_length=10, choices=[
        ('activa', 'Activa'),
        ('completada', 'Completada'),
        ('cancelada', 'Cancelada'),
    ], default='activa')
    capacidad_maxima = models.IntegerField(default=10)  # Capacidad del vehículo
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.SET_NULL, null=True, blank=True)  # Vehículo asignado
    frecuencia = models.CharField(max_length=50, choices=[
        ('diaria', 'Diaria'),
        ('semanal', 'Semanal'),
        ('mensual', 'Mensual')
    ], default='diaria')  # Frecuencia de la ruta
    alumnos = models.ManyToManyField(Alumno, related_name="rutas_alumnos")  # Alumnos asignados a la ruta
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.nombre} - {self.conductor.nombre} {self.conductor.apellido}"



class Viaje(models.Model):
    # Campos del viaje
    conductor = models.ForeignKey('Conductor', on_delete=models.CASCADE)  # Relación con el modelo Conductor
    apoderado = models.ForeignKey('Apoderado', on_delete=models.CASCADE, null=True, blank=True)  # Permitir nulos
    vehiculo = models.ForeignKey('Vehiculo', on_delete=models.CASCADE)  # Relación con el modelo Vehículo
    ruta = models.ForeignKey(Ruta, on_delete=models.CASCADE)
    alumnos = models.ManyToManyField(Alumno, related_name='viajes')  # Relación con alumnos

    # Otros campos del viaje
    fecha_salida = models.DateTimeField(default=timezone.now)  # Fecha y hora de salida, con valor por defecto
    fecha_llegada = models.DateTimeField(null=True, blank=True)  # Fecha y hora de llegada, puede ser nulo
    direccion = models.CharField(max_length=255)  # Campo para la dirección en lugar de ubicación
    estado_viaje = models.CharField(max_length=50, choices=[
        ('en_progreso', 'En progreso'),
        ('finalizado', 'Finalizado'),
        ('cancelado', 'Cancelado'),
    ], default='en_progreso')  # Estado del viaje

    # Otros campos según sea necesario

    def __str__(self):
        return f"Viaje {self.id} - {self.estado_viaje}"

    class Meta:
        verbose_name = 'Viaje'
        verbose_name_plural = 'Viajes'





###########

class SolicitudVinculacion(models.Model):
    apoderado = models.ForeignKey('Apoderado', on_delete=models.CASCADE)
    conductor = models.ForeignKey('Conductor', on_delete=models.CASCADE)
    alumnos = models.ManyToManyField('Alumno')  # Relación con los alumnos

    ESTADOS = [
        ('pendiente', 'Pendiente'),
        ('aceptada', 'Aceptada'),
        ('rechazada', 'Rechazada'),
    ]
    
    estado = models.CharField(max_length=20, choices=ESTADOS, default='pendiente')

    def __str__(self):
        return f"Solicitud de {self.apoderado} para {self.conductor} - Estado: {self.estado}"

    class Meta:
        verbose_name = "Solicitud de Vinculación"
        verbose_name_plural = "Solicitudes de Vinculación"
    


class SubirDumentoImagen(models.Model):
    documento = models.FileField(upload_to='documents/')
    imagen = models.ImageField(upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    conductor = models.ForeignKey('Conductor', on_delete=models.CASCADE, related_name='documentos', null=True, blank=True)

    class Meta:
        db_table = "¨files"
        ordering = ['-created_at']



class DocumentosPersonales(models.Model):

app/templates/conductor/elegir_ruta.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elegir Ruta</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f7f9fc;
            color: #333;
        }

        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 30px;
        }

        #ruta-lista {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        ul {
            list-style-type: none;
            padding: 0;
        }

        li {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px;
            border-bottom: 1px solid #ddd;
            transition: background-color 0.3s;
        }

        li:last-child {
            border-bottom: none;
        }

        li:hover {
            background-color: #f1f1f1;
        }

        strong {
            font-size: 18px;
        }

        button {
            background-color: #28a745;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 10px 15px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        button:hover {
            background-color: #218838;
        }

        @media (max-width: 600px) {
            li {
                flex-direction: column;
                align-items: flex-start;
            }

            button {
                width: 100%;
                margin-top: 10px;
            }
        }
    </style>
</head>
<body>
    {% block content %}
    <h1>Elige una Ruta</h1>

    <div id="ruta-lista">
        <ul>
            {% for ruta in rutas %}
                <li>
                    <strong>{{ ruta.nombre }}</strong>
                    <button onclick="elegirRuta({{ ruta.id }})">Elegir</button>
                </li>
            {% endfor %}
        </ul>
    </div>

    <script>
    function elegirRuta(rutaId) {
        // Redirigir a la vista de visualización de recorrido
        window.location.href = `/visualizar-recorrido/${rutaId}/`; // Cambia la URL según sea necesario
    }
    </script>
    {% endblock %}
</body>
</html>

app/templates/conductor/gestionar_documentos.html
{% block content %}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .document-container {
            display: flex;
            justify-content: space-between; /* Espacio entre las secciones */
            margin-bottom: 20px;
        }

        .document-section {
            background-color: rgba(255, 255, 255, 0.9);
            border-radius: 10px;
            padding: 20px;
            flex: 1; /* Ajusta el tamaño de cada sección */
            margin-right: 10px;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
        }

        .document-section:last-child {
            margin-right: 0; /* Elimina el margen derecho en el último elemento */
        }

        .document-item {
            display: flex;
            align-items: center; /* Centra verticalmente el contenido */
            justify-content: space-between; /* Espacio entre los elementos */
            margin-bottom: 10px; /* Espacio entre cada documento */
            background-color: #f8f9fa; /* Color de fondo para los documentos */
            padding: 10px; /* Espacio interno */
            border-radius: 5px; /* Bordes redondeados */
        }

        .document-actions {
            display: flex;
            align-items: center; /* Centra verticalmente los botones */
        }

        .btn-icon {
            display: flex;
            align-items: center; /* Centra verticalmente el icono */
            padding: 5px; /* Espacio alrededor del icono */
            margin-left: 10px; /* Espacio entre los iconos */
            color: white; /* Color del texto de los botones */
            border: none; /* Sin borde */
            border-radius: 5px; /* Bordes redondeados */
            transition: background-color 0.3s; /* Efecto al pasar el ratón */
        }

        .btn-view {
            background-color: #007bff; /* Color de fondo para ver documento */
        }

        .btn-view:hover {
            background-color: #0056b3; /* Color al pasar el ratón */
        }

        .btn-delete {
            background-color: #dc3545; /* Color de fondo para eliminar */
        }

        .btn-delete:hover {
            background-color: #c82333; /* Color al pasar el ratón */
        }

        .welcome-text {
            font-size: 24px;
            margin-bottom: 20px;
        }

        .document-title {
            font-weight: bold;
            margin-right: 10px; /* Espacio entre el título y los documentos */
        }
    </style>
</head>

<div class="header">
    <h2 class="welcome-text">Gestionar Documentos</h2>
</div>

{% if mensaje %}
    <div class="alert alert-success" role="alert">
        {{ mensaje }}
    </div>
{% endif %}

<div class="document-container">
    <!-- Rectángulo para Documentos Personales -->
    <div class="document-section personal-documents">
        <h2>Mis datos</h2>
        <p><strong>Nombre:</strong> {{ user.nombre }}</p>
        <p><strong>Apellido:</strong> {{ user.apellido }}</p>
        <p><strong>RUT:</strong> {{ user.rut }}</p>
        <div class="document-item">
            <span class="document-title">Licencia:</span>
            <div class="document-actions">
                {% if documentos_personales.licencia %}
                    <a href="{{ documentos_personales.licencia.url }}" target="_blank" class="btn-icon btn-view">
                        <i class="fas fa-eye"></i> <!-- Icono de ojo -->
                    </a>
                    <form method="POST" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="documento_id" value="{{ documentos_personales.id }}">
                        <button type="submit" name="eliminar_documento_licencia" class="btn-icon btn-delete">
                            <i class="fas fa-trash"></i> <!-- Icono de basura -->
                        </button>
                    </form>
                {% else %}
                    No tienes licencia subida.
                {% endif %}
            </div>
        </div>
        <div class="document-item">
            <span class="document-title">Certificado:</span>
            <div class="document-actions">
                {% if documentos_personales.certificado %}
                    <a href="{{ documentos_personales.certificado.url }}" target="_blank" class="btn-icon btn-view">
                        <i class="fas fa-eye"></i> <!-- Icono de ojo -->
                    </a>
                    <form method="POST" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="documento_id" value="{{ documentos_personales.id }}">
                        <button type="submit" name="eliminar_documento_certificado" class="btn-icon btn-delete">
                            <i class="fas fa-trash"></i> <!-- Icono de basura -->
                        </button>
                    </form>
                {% else %}
                    No tienes certificado subido.
                {% endif %}
            </div>
        </div>
    </div>

    <!-- Rectángulo para Documentos del Vehículo -->
    <div class="document-section vehicle-documents">
        <h2>Documentos del Vehículo</h2>
        <ul>
            {% if vehiculo %}
                <li>
                    <i class="fas fa-car"></i>
                    <strong>Marca:</strong> {{ vehiculo.marca }}
                </li>
                <li>
                    <i class="fas fa-car"></i>
                    <strong>Modelo:</strong> {{ vehiculo.modelo }}
                </li>
                <li>
                    <i class="fas fa-calendar-alt"></i>
                    <strong>Año:</strong> {{ vehiculo.anio }}
                </li>
                <li>
                    <i class="fas fa-tag"></i>
                    <strong>Patente:</strong> {{ vehiculo.patente }}
                </li>
                {% for documento in documentos_vehiculo %}
                    <li>
                        <i class="fas fa-file-alt"></i>
                        <strong>{{ documento.tipo_documento|capfirst }}:</strong>
                        <a href="{{ documento.archivo.url }}" target="_blank" class="btn btn-primary btn-icon">
                            <i class="fas fa-eye"></i> <!-- Icono de ojo -->
                        </a>
                        <form method="POST" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="documento_id" value="{{ documento.id }}">
                            <button type="submit" name="eliminar_documento_vehiculo" class="btn btn-danger btn-icon">
                                <i class="fas fa-trash"></i> <!-- Icono de basura -->
                            </button>
                        </form>
                        <a href="{% url 'editar_documento' documento.id %}" class="btn btn-warning btn-icon">Editar</a>
                    </li>
                {% endfor %}
            {% else %}
                <li><i class="fas fa-exclamation-circle"></i>No tienes datos de vehículo registrados.</li>
            {% endif %}
        </ul>
    </div>
    <a href="{% url 'gestionar_vehiculos' %}" class="btn btn-primary">Gestionar Vehículos</a>

</div>

{% endblock %}

app/templates/conductor/subir_documentos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subir Documentos Personales</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet"> <!-- Íconos -->
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f4f4f4;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #333;
            margin: 0;
            overflow: hidden;
        }

        .container {
            width: 60%;
            max-width: 500px;
            background: #ffffff;
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
            text-align: center;
        }

        h2 {
            color: #007bff;
            margin-bottom: 30px;
            text-transform: uppercase;
            font-weight: bold;
        }

        .form-group {
            margin-bottom: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .custom-file-btn {
            width: 100%;
            background-color: transparent;
            border: 2px solid #000;
            padding: 15px;
            border-radius: 5px;
            cursor: pointer;
            color: #000;
            font-size: 16px;
            text-transform: uppercase;
            margin-bottom: 10px;
            transition: all 0.3s;
        }

        .custom-file-btn:hover {
            background-color: #eaeaea;
        }

        .btn {
            width: 100%;
            background-color: #ffcc00;
            color: white;
            border: none;
            font-weight: bold;
            padding: 15px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .btn:hover {
            background-color: #ffc107;
        }

        .status-icon {
            margin-left: 10px;
            color: green;
            display: none;
        }

        .status-icon.success {
            display: inline-block;
        }

        input[type="file"] {
            display: none; /* Ocultar el input de archivo */
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>sube tus documentos</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label class="custom-file-btn" for="id_licencia" id="licencia-label">LICENCIA</label>
                <input type="file" id="id_licencia" name="licencia" accept=".pdf,.jpg,.png" onchange="updateLabel('licencia')">
                <span class="status-icon" id="licencia-status">✔</span>
            </div>

            <div class="form-group">
                <label class="custom-file-btn" for="id_certificado" id="certificado-label">CERTIFICADO</label>
                <input type="file" id="id_certificado" name="certificado" accept=".pdf,.jpg,.png" onchange="updateLabel('certificado')">
                <span class="status-icon" id="certificado-status">✔</span>
            </div>

            <button type="submit" class="btn">Subir Documentos</button>
        </form>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.7.6/lottie.min.js"></script>
    <script>
        // Actualizar la etiqueta y mostrar el icono de éxito al seleccionar un archivo
        function updateLabel(field) {
            const inputFile = document.getElementById(`id_${field}`);
            const label = document.getElementById(`${field}-label`);
            const statusIcon = document.getElementById(`${field}-status`);

            if (inputFile.files.length > 0) {
                // Actualizar el texto del botón con el nombre del archivo seleccionado
                label.textContent = inputFile.files[0].name;
                statusIcon.classList.add('success');
            }
        }
    </script>
</body>
</html>